services:
  txe:
    image: "aztecprotocol/aztec"
    environment:
      LOG_LEVEL: # Loaded from the user shell if explicitly set
      HOST_WORKDIR: "${PWD}" # Loaded from the user shell to show log files absolute path in host
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
      - ${HOME}:${HOME}
    # We are exposing the port so we
    # can connect to the txe from localhost
    ports:
      - 8081:8081
    command: start --txe --port 8081
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8081/status"]
      interval: 1s
      timeout: 1s
      retries: 10


  # This service is a hack for waiting until the
  # txe is healthy - since we will not be running
  # nargo from docker
  healthcheck:
    image: "bash:4.4"
    command: "bash echo 'TXE ready'"
    depends_on:
      txe:
        condition: service_healthy

  # We won't be using the productive image on nargo
  # we will be using a local build of it
  # aztec-nargo:
  #   image: "aztecprotocol/aztec-nargo"
  #   environment:
  #     HOME: # Loaded from the user shell
  #     NARGO_FOREIGN_CALL_TIMEOUT: "${NARGO_FOREIGN_CALL_TIMEOUT}" # To avoid timeouts when many tests run at once
  #   working_dir: "${WORKDIR}"
  #   command: "${TEST_ARGS}"
  #   volumes:
  #     - ${HOME}:${HOME}
  #   depends_on:
  #     txe:
  #       condition: service_healthy
